export const modelBindingErrors = {
  'en-US': { conflict: 'This binding changed elsewhere. Refresh and review it before trying again.', unknown: 'The result is not confirmed. Refresh to confirm it before making another change.', failed: 'The change could not be completed. Review the current binding before trying again.', version: 'Refresh this page before changing the binding.' },
  'zh-CN': { conflict: '绑定已被其他操作更改，请刷新并确认后重试。', unknown: '操作结果尚未确认，请刷新确认后再进行修改。', failed: '操作未能完成，请确认当前绑定后重试。', version: '请刷新页面后再修改绑定。' },
  'zh-TW': { conflict: '綁定已被其他操作變更，請重新整理並確認後再試。', unknown: '操作結果尚未確認，請重新整理確認後再修改。', failed: '操作未能完成，請確認目前綁定後再試。', version: '請重新整理頁面後再修改綁定。' },
  ja: { conflict: '別の操作で割り当てが変更されました。更新して確認してから再試行してください。', unknown: '操作結果は未確認です。更新して確認してから変更してください。', failed: '操作を完了できませんでした。現在の割り当てを確認して再試行してください。', version: 'ページを更新してから割り当てを変更してください。' },
  ko: { conflict: '다른 작업에서 연결이 변경되었습니다. 새로 고침 후 확인하고 다시 시도하세요.', unknown: '작업 결과가 확인되지 않았습니다. 새로 고침하여 확인한 뒤 변경하세요.', failed: '작업을 완료하지 못했습니다. 현재 연결을 확인하고 다시 시도하세요.', version: '페이지를 새로 고친 후 연결을 변경하세요.' },
  es: { conflict: 'Otra operación cambió la asignación. Actualiza y revísala antes de reintentar.', unknown: 'El resultado no está confirmado. Actualiza para confirmarlo antes de modificarlo.', failed: 'No se pudo completar el cambio. Revisa la asignación actual antes de reintentar.', version: 'Actualiza la página antes de cambiar la asignación.' },
  pt: { conflict: 'Outra operação alterou a associação. Atualize e confira antes de tentar novamente.', unknown: 'O resultado não foi confirmado. Atualize para confirmar antes de alterar.', failed: 'Não foi possível concluir a alteração. Confira a associação atual antes de tentar novamente.', version: 'Atualize a página antes de alterar a associação.' },
  ru: { conflict: 'Привязка изменена другой операцией. Обновите и проверьте её перед повторной попыткой.', unknown: 'Результат пока не подтверждён. Обновите страницу для подтверждения перед изменением.', failed: 'Не удалось завершить изменение. Проверьте текущую привязку перед повторной попыткой.', version: 'Обновите страницу перед изменением привязки.' },
}
