# -*- coding: utf-8 -*-
# Copyright 2025-2026 Project N.E.K.O. Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Game Router package.

Formerly the monolithic ``main_routers/game_router.py``; now split into pure
helper domains plus a layered state-machine core (clean DAG):
``runtime`` (endpoints + ``_run_game_chat``) -> ``postgame`` (delivery +
finalize) -> ``session_pool`` (``_game_sessions`` lifecycle) ->
``route_lifecycle`` (route-state transitions, heartbeat, organizer glue).
Mutable containers are module-level singletons shared across the layers by
reference (from-imports never copy them).

Note for tests: ``monkeypatch.setattr`` must target the submodule that
*consumes* a helper, not this package facade -- re-exports are snapshots.
Use ``tests/unit/game_route_test_helpers.gr_patch_all`` to hit every
submodule holding a binding.

URL convention: routes declared WITHOUT trailing slash; enforced by
``scripts/check_api_trailing_slash.py``.
"""

from utils.game_route_state import (  # noqa: F401  (re-exports: websocket_router + tests touch these)
    _game_route_states,
    _get_active_game_route_state,
    _get_route_lock,
    _get_supersede_lock,
    _route_state_key,
    is_game_route_active,
)

from ._shared import (  # noqa: F401
    logger,
    router,
    _DEFAULT_LAST_FULL_DIALOGUE_COUNT,
    _ACCIDENTAL_GAME_ENTRY_GRACE_MS,
    _GAME_DEBUG_MATERIAL_LOG_LIMIT,
    _log_game_debug_material,
    _infer_service_source,
    _strip_json_fence,
    _normalize_short_text,
    _is_repeated_neko_invite,
    _coerce_payload_bool,
    _coerce_payload_float,
)
from .vision import game_sdk_vision_analyze  # noqa: F401
from .char_info import (  # noqa: F401
    _extract_request_language_full,
    _absorb_request_language,
    _resolve_game_prompt_language,
    _format_game_character_profile_prompt,
    _get_character_info,
    _get_current_character_info,
    _get_game_route_summary_llm_info,
    _normalize_game_character_profile_value,
    _ordered_game_character_profile_keys,
    _replace_game_character_profile_placeholders,
)
from .logs import (  # noqa: F401
    _game_log_payload_flag_is_true,
    game_logs,
    game_log_view,
    game_log_enable,
    game_log_ingest,
)
from .memory_policy import (  # noqa: F401
    _DEFAULT_GAME_MEMORY_TAIL_COUNT,
    _MAX_GAME_MEMORY_TAIL_COUNT,
    _DEFAULT_SOCCER_GAME_MEMORY_ENABLED,
    _SOCCER_GAME_MEMORY_POLICY_FIELDS,
    _DEFAULT_BADMINTON_GAME_MEMORY_ENABLED,
    _BADMINTON_GAME_MEMORY_POLICY_FIELDS,
    _normalize_game_memory_tail_count,
    _normalize_soccer_game_memory_enabled,
    _payload_bool_from_keys,
    _GAME_MEMORY_POLICY_PAYLOAD_KEYS,
    _SOCCER_GAME_MEMORY_PAYLOAD_KEYS,
    _BADMINTON_GAME_MEMORY_PAYLOAD_KEYS,
    _normalize_game_memory_type,
    _game_memory_policy_fields,
    _game_memory_payload_keys,
    _game_memory_default_enabled,
    _sync_generic_game_memory_aliases,
    _game_memory_policy,
    _soccer_game_memory_policy,
    _badminton_game_memory_policy,
    _game_memory_policy_from_payload,
    _soccer_game_memory_policy_from_payload,
    _badminton_game_memory_policy_from_payload,
    _game_memory_player_interaction_enabled,
    _game_memory_event_reply_enabled,
    _game_memory_archive_enabled,
    _game_memory_postgame_context_enabled,
    _soccer_game_memory_player_interaction_enabled,
    _soccer_game_memory_event_reply_enabled,
    _soccer_game_memory_archive_enabled,
    _soccer_game_memory_postgame_context_enabled,
    _game_memory_enabled,
    _game_memory_camel_key,
    _attach_game_memory_flag_to_event,
)
from .game_context import (  # noqa: F401
    _GAME_CONTEXT_ORGANIZE_TRIGGER_COUNT,
    _GAME_CONTEXT_RECENT_KEEP_COUNT,
    _GAME_CONTEXT_RECENT_WINDOW_MAX_COUNT,
    _GAME_CONTEXT_FAILURE_VISIBLE_WINDOW_MAX_COUNT,
    _GAME_CONTEXT_FAILURE_FALLBACK_KEEP_COUNT,
    _GAME_CONTEXT_FINALIZE_WAIT_SECONDS,
    _GAME_CONTEXT_SIGNAL_GROUPS,
    _LEGACY_SIGNAL_GROUP_ALIASES,
    _GAME_CONTEXT_MAX_SIGNALS_PER_GROUP,
    _GAME_CONTEXT_MAX_EVIDENCE_PER_SIGNAL,
    _normalize_text_items,
    _empty_game_context_signals,
    _normalize_signal_label,
    _normalize_game_context_evidence,
    _normalize_game_context_signal_entry,
    _normalize_game_context_signals,
    _merge_game_context_evidence,
    _merge_game_context_signals,
    _normalize_game_context_organizer_state,
    _dialog_id_index,
    _game_context_recent_dialogues,
    _game_context_dialog_lines,
    _signals_compact_for_prompt,
    _compact_nonempty_game_context_signals,
    _game_context_signals_text,
    _format_game_context_for_prompt,
    _build_game_context_prompt_payload,
    _build_game_context_organizer_payload,
    _run_game_context_organizer_ai,
    _format_ts,
    _extract_score_text,
    _GAME_EVENT_MEMORY_LABEL_KEYS,
    _dialog_memory_line,
    _game_dialog_item_allowed_for_memory,
)
from .pregame import (  # noqa: F401
    _SOCCER_MOODS,
    _SOCCER_DIFFICULTIES,
    _SOCCER_DEFAULT_DIFFICULTIES,
    _SOCCER_GAME_STANCES,
    _soccer_random_default_difficulty,
    _default_soccer_pregame_context,
    _normalize_soccer_pregame_context,
    _format_soccer_pregame_context_for_prompt,
    _BADMINTON_EXPRESSIONS,
    _BADMINTON_INTENSITIES,
    _default_badminton_pregame_context,
    _normalize_badminton_pregame_context,
    _format_badminton_pregame_context_for_prompt,
    _fetch_recent_history_for_pregame,
    _run_pregame_context_ai,
    _run_soccer_pregame_context_ai,
    _build_soccer_pregame_context,
    _build_badminton_pregame_context,
)
from .visible_events import (  # noqa: F401
    _normalize_badminton_shot_type,
    _GAME_INTERNAL_LOG_PREFIX_RE,
    _GAME_CONTROL_PAREN_TRAIL_RE,
    _GAME_CONTROL_JSON_TRAIL_RE,
    _GAME_INTERNAL_CONTROL_LINE_RE,
    _GAME_INTERNAL_ADVICE_RE,
    _GAME_LLM_VISIBLE_EVENT_TOP_LEVEL_DROP_KEYS,
    _SOCCER_LLM_VISIBLE_SNAPSHOT_DROP_KEYS,
    _sanitize_game_visible_line,
    _sanitize_soccer_llm_visible_snapshot,
    _build_game_llm_visible_event,
    _sanitize_badminton_duel_state,
    _sanitize_badminton_attempts_results,
    _sanitize_badminton_event,
)
from .balance import (  # noqa: F401
    _SOCCER_ANGER_PRESSURE_CAP_WEAK,
    _SOCCER_ANGER_PRESSURE_CAP_DEFAULT,
    _SOCCER_ANGER_PRESSURE_CAP_STRONG,
    _SOCCER_EMOTION_INERTIA,
    _build_soccer_balance_hint,
    _soccer_context_text_blob,
    _soccer_anger_pressure_cap_applicable,
    _soccer_anger_pressure_cap_goals,
    _build_soccer_anger_pressure_cap,
    _event_current_difficulty,
    _apply_soccer_anger_pressure_cap,
    _safe_int,
    _build_badminton_duel_balance_hint,
    _badminton_duel_event_shooter,
    _build_badminton_duel_anger_pressure_cap,
    _apply_badminton_anger_pressure_cap,
)
from .badminton_scores import (  # noqa: F401
    _BADMINTON_SCORE_SESSION_TTL_SECONDS,
    _BADMINTON_SCORING_MODES,
    _BADMINTON_GAME_TYPES,
    _BADMINTON_SHOT_TYPE_ALIASES,
    _badminton_recent_score_sessions,
    _BADMINTON_SCORES_DB_PATH,
    _BADMINTON_LEGACY_SCORES_DB_PATH,
    _is_badminton_game_type,
    _normalize_badminton_mode,
    _is_badminton_scoring_mode,
    _normalize_badminton_non_negative_int,
    _normalize_badminton_distance,
    _BADMINTON_PX_PER_METER,
    _format_badminton_distance_meters,
    _score_db_game_slug,
    _get_badminton_scores_db_path,
    _prepare_badminton_scores_db_path,
    _open_badminton_scores_db,
    _ensure_badminton_scores_schema,
    _badminton_score_rows,
    _badminton_rank_for_row,
    _badminton_row_to_public_dict,
    _badminton_player_identity,
    _badminton_score_totals_from_data,
    _badminton_score_totals_match_submission,
    _prune_badminton_score_sessions,
    _remember_badminton_score_session,
    _badminton_end_payload_completed_round,
    _badminton_score_session_key_from_payload,
    _badminton_score_submission_allowed,
    _badminton_score_data_for_insert,
    _release_badminton_score_session_reservation,
    _consume_badminton_score_session,
    _badminton_leaderboard_total_players,
    _badminton_leaderboard_total_scores,
    _badminton_personal_best,
    _badminton_insert_score,
    game_badminton_leaderboard,
    game_badminton_leaderboard_submit,
)
from .archive import (  # noqa: F401
    _route_game_started_elapsed_ms,
    _game_archive_memory_skip_reason,
    _build_game_archive_memory_skipped_result,
    _summarize_game_archive,
    _build_game_archive,
    _archive_game_context_degraded,
    _archive_prompt_language,
    _build_game_archive_memory_text,
    _archive_last_assistant_line,
    _archive_last_user_text,
    _normalize_memory_highlight_text,
    _normalize_game_archive_memory_highlights,
    _fallback_game_archive_memory_highlights,
    _build_game_archive_memory_highlight_source,
    _select_game_archive_memory_highlights,
    _ensure_game_archive_memory_highlights,
    _game_dialog_tail_for_memory,
    _game_dialog_item_to_memory_message,
    _build_game_archive_tail_memory_messages,
    _build_game_archive_memory_summary_text,
    _build_game_archive_memory_messages,
    _archive_score_text,
    _submit_game_archive_to_memory,
)
from .route_lifecycle import (  # noqa: F401
    _GAME_ROUTE_ACTIVATION_LOG_LIMIT,
    _push_game_window_state_change,
    _TAKEOVER_CALLBACK_INBOX_KEY,
    _close_takeover_callback_inbox,
    _GAME_ROUTE_OUTPUT_LIMIT,
    _GAME_ROUTE_HEARTBEAT_INTERVAL_SECONDS,
    _GAME_ROUTE_HEARTBEAT_TIMEOUT_SECONDS,
    _GAME_ROUTE_HIDDEN_HEARTBEAT_TIMEOUT_SECONDS,
    _GAME_ROUTE_HEARTBEAT_SWEEP_SECONDS,
    _detect_before_game_external_state,
    _find_game_route_state_for_session,
    _build_route_state,
    _activate_game_route,
    _append_route_activation,
    _next_game_dialog_id,
    _sync_game_dialog_seq_from_id,
    _game_context_pending_dialogues,
    _game_context_recent_id_limit,
    _apply_game_context_failure_fallback,
    _set_game_context_recent_ids,
    _should_schedule_game_context_organizer,
    _maybe_schedule_game_context_organizer,
    _append_game_dialog,
    _append_game_output,
    _apply_game_context_organizer_success,
    _apply_game_context_organizer_failure,
    _run_game_context_organizer_task,
    _settle_game_context_organizer_before_archive,
    _cancel_game_context_organizer_before_disabled_archive,
    _route_liveness_at,
    _route_heartbeat_expired,
    _route_heartbeat_timeout_seconds,
    _update_route_visibility_from_payload,
    _update_game_memory_enabled_from_payload,
    _update_route_start_state_from_payload,
)
from .session_pool import (  # noqa: F401
    _game_sessions,
    _SESSION_TIMEOUT_SECONDS,
    _SESSION_CLEANUP_SWEEP_SECONDS,
    _game_session_create_locks,
    _get_session_create_lock,
    _build_game_prompt,
    _get_or_create_session,
    _build_and_register_game_session,
    _refresh_game_session_instructions,
    _game_session_key,
    _POSTGAME_SESSION_MARKER,
    _POSTGAME_UUID_TAIL_RE,
    _make_postgame_session_id,
    _route_session_id,
    _parse_game_session_key,
    _close_and_remove_session,
)
from .author_prompt import (  # noqa: F401
    _AUTHOR_PROMPT_MODE,
    _AUTHOR_PROMPT_ROLES,
    _AUTHOR_PROMPT_MAX_MESSAGES,
    _AUTHOR_PROMPT_MAX_CONTENT_CHARS,
    _AUTHOR_PROMPT_MAX_TOTAL_CHARS,
    _normalize_author_managed_prompt,
    _build_author_managed_messages,
    _run_author_managed_game_chat,
)
from .postgame import (  # noqa: F401
    _POSTGAME_SKIP_REASONS,
    _POSTGAME_REALTIME_NUDGE_DELAYS,
    _POSTGAME_REALTIME_UNORGANIZED_LIMIT,
    _POSTGAME_REALTIME_UNORGANIZED_MAX_TOKENS,
    _normalize_postgame_options,
    _postgame_last_signals,
    _archive_unorganized_dialogues,
    _append_token_limited_lines,
    _build_game_postgame_context_text,
    _build_game_postgame_realtime_nudge_instruction,
    _build_game_postgame_event,
    _active_realtime_session,
    _is_gemini_realtime_session,
    _run_postgame_realtime_nudge_task,
    _postgame_context_request_id,
    _deliver_postgame_to_realtime,
    _deliver_postgame_text_bubble,
    _deliver_game_postgame,
    _finalize_game_route_state,
    _build_postgame_context_snapshot,
    _finalize_game_route_state_inner,
)
from .runtime import (  # noqa: F401
    _EXTERNAL_VOICE_DEDUP_TTL_SECONDS,
    _EXTERNAL_VOICE_DEDUP_MAX_ENTRIES,
    _SSML_TAG_PATTERN,
    _SOCCER_QUICK_LINE_KEYS,
    _BADMINTON_QUICK_LINE_KEYS,
    _badminton_quick_lines_cache,
    _BADMINTON_QUICK_LINES_CACHE_MAX,
    _badminton_chat_rate_windows,
    _BADMINTON_CHAT_RATE_WINDOW_SECONDS,
    _BADMINTON_CHAT_RATE_MAX,
    _game_dialog_history_user_text,
    _game_dialog_history_assistant_text,
    _build_game_recent_history_messages,
    _reset_game_session_text_history_for_turn,
    _normalize_quick_lines,
    _get_badminton_quick_lines_fallback,
    _public_route_state,
    _game_route_stale_session_response,
    _game_route_closed_session_response,
    _resolve_lanlan_name,
    _parse_control_instructions,
    _strip_ssml_like_tags,
    _check_badminton_chat_rate,
    _run_game_chat,
    game_chat,
    game_route_start,
    game_route_state,
    game_route_any_active,
    game_route_drain,
    game_route_voice_transcript,
    game_route_heartbeat,
    game_route_end,
    _speak_game_line_via_project_tts,
    _project_tts_pipeline_state,
    _game_route_event_has_user_input,
    _mirror_game_assistant_text,
    game_project_mirror_assistant,
    game_project_speak,
    _build_external_text_event,
    _build_external_voice_event,
    _build_external_user_event,
    _route_external_transcript_to_game,
    route_external_voice_transcript,
    finalize_game_routes_for_character,
    route_external_stream_message,
    _compact_realtime_context_text,
    game_realtime_context,
    _complete_game_end_from_payload,
    game_end,
    game_quick_lines,
    game_character,
    cleanup_expired_sessions,
)
