function escapeHtml(value: string) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function escapeAttribute(value: string) {
  return escapeHtml(value).replace(/'/g, '&#39;')
}

function renderInlineMarkdown(value: string) {
  const escaped = escapeHtml(value)
  return escaped
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g, (_match, label, url) => {
      const safeUrl = escapeAttribute(String(url).replace(/&amp;/g, '&'))
      return `<a href="${safeUrl}" target="_blank" rel="noopener noreferrer">${label}</a>`
    })
}

function renderMarkdownToHtml(markdown: string) {
  const lines = markdown.replace(/\r\n/g, '\n').split('\n')
  const html: string[] = []
  let inCode = false
  let codeLines: string[] = []
  let inList = false
  const closeList = () => {
    if (inList) {
      html.push('</ul>')
      inList = false
    }
  }

  for (const line of lines) {
    const fence = line.match(/^```/)
    if (fence) {
      if (inCode) {
        html.push(`<pre><code>${escapeHtml(codeLines.join('\n'))}</code></pre>`)
        codeLines = []
        inCode = false
      } else {
        closeList()
        inCode = true
      }
      continue
    }
    if (inCode) {
      codeLines.push(line)
      continue
    }
    if (!line.trim()) {
      closeList()
      continue
    }
    const heading = line.match(/^(#{1,3})\s+(.+)$/)
    if (heading) {
      closeList()
      const level = heading[1]?.length || 1
      html.push(`<h${level}>${renderInlineMarkdown(heading[2] || '')}</h${level}>`)
      continue
    }
    const listItem = line.match(/^\s*[-*]\s+(.+)$/)
    if (listItem) {
      if (!inList) {
        html.push('<ul>')
        inList = true
      }
      html.push(`<li>${renderInlineMarkdown(listItem[1] || '')}</li>`)
      continue
    }
    const quote = line.match(/^>\s?(.+)$/)
    if (quote) {
      closeList()
      html.push(`<blockquote>${renderInlineMarkdown(quote[1] || '')}</blockquote>`)
      continue
    }
    closeList()
    html.push(`<p>${renderInlineMarkdown(line)}</p>`)
  }
  closeList()
  if (inCode) {
    html.push(`<pre><code>${escapeHtml(codeLines.join('\n'))}</code></pre>`)
  }
  return html.join('\n')
}

// Inline click-interceptor: the markdown document is loaded into a sandboxed
// iframe (sandbox="allow-scripts", no allow-popups), so `<a target="_blank">`
// generated by renderInlineMarkdown cannot navigate on its own. Route the
// click through the parent via postMessage so HostedSurfaceFrame can hand
// the URL to openExternalUrl — same trapped-webview fix we apply elsewhere
// (frontend/react-neko-chat/src/openExternal.ts, src/utils/openExternal.ts).
const MARKDOWN_LINK_INTERCEPTOR_SCRIPT = `
<script>
(function () {
  document.addEventListener('click', function (event) {
    var el = event.target;
    while (el && el !== document.body) {
      if (el.tagName === 'A' && el.getAttribute('href')) {
        var href = el.getAttribute('href');
        if (/^https?:\\/\\//i.test(href)) {
          event.preventDefault();
          window.parent.postMessage({
            type: 'neko-hosted-surface-open-external',
            payload: { url: href },
          }, '*');
        }
        return;
      }
      el = el.parentNode;
    }
  }, true);
})();
<\/script>`

export function buildMarkdownDocument(source: string, title: string, locale: string) {
  return `<!doctype html>
<html lang="${escapeAttribute(locale)}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    :root { color-scheme: light dark; }
    body { margin: 0; padding: 24px; font: 14px/1.7 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #1f2937; background: #fff; }
    main { max-width: 880px; margin: 0 auto; }
    h1, h2, h3 { line-height: 1.25; color: #111827; }
    h1 { font-size: 28px; margin: 0 0 20px; }
    h2 { font-size: 22px; margin: 28px 0 12px; }
    h3 { font-size: 17px; margin: 22px 0 10px; }
    p, ul, blockquote, pre { margin: 12px 0; }
    ul { padding-left: 22px; }
    code { padding: 2px 5px; border-radius: 5px; background: #f3f4f6; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
    pre { overflow: auto; padding: 14px; border-radius: 10px; background: #111827; color: #f9fafb; }
    pre code { padding: 0; background: transparent; color: inherit; }
    blockquote { padding: 8px 14px; border-left: 4px solid #93c5fd; background: #eff6ff; color: #374151; }
    a { color: #2563eb; }
    @media (prefers-color-scheme: dark) {
      body { color: #e5e7eb; background: #111827; }
      h1, h2, h3 { color: #f9fafb; }
      code { background: #1f2937; }
      blockquote { background: #172554; color: #dbeafe; }
      a { color: #93c5fd; }
    }
  </style>
</head>
<body>
  <main>
    <h1>${escapeHtml(title)}</h1>
    ${renderMarkdownToHtml(source)}
  </main>
  ${MARKDOWN_LINK_INTERCEPTOR_SCRIPT}
</body>
</html>`
}
